### ISSUE TITLE
rstudio-workbench pod metadata labels

### ISSUE THREAD

**Issue by samssann** [rstudio/helm#101]
Is there a way to add a metadata label to the pod template using the rstudio-workbench helm chart values.yaml?
This is what i need the workbench pod to look like:
```
apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: <aad_pod_identity_name>
```
