### ISSUE TITLE
Specify `selector` for persistent volume claims

### ISSUE THREAD

**Issue by d-m** [rstudio/helm#136]
My team often has several development instances of RStudio Workbench deployed at any time. We'd like to be able to leverage creating the `homeStorage` persistent volume claim, but with NFS persistent volumes it's sometimes tricky to make sure that the claim binds to the correct volume. We leverage the `selector` feature of persistent volume  to make sure the bind happens correctly.

For example, we define the spec for the PVC like so:

```
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-workbench-deployment
      pv-role: home
```

and it then binds to a persistent volume matching those labels.

It would be helpful if we could define a `selector` block when creating a persistent volume claim, which would go here:

https://github.com/rstudio/helm/blob/f73fdd04cecfaead6d48f230e2ae722728448ed4/charts/rstudio-workbench/templates/pvc.yaml#L38

Here's the Kubernetes documentation for it: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
