### ISSUE TITLE
RStudio Workbench Load Balancing

### ISSUE THREAD

**Issue by d-m** [rstudio/helm#137]
The [readme](https://github.com/rstudio/helm/blob/f73fdd04cecfaead6d48f230e2ae722728448ed4/charts/rstudio-workbench/README.md?plain=1#L53) seems to indicate that setting replicas > 1 should be enough to enable load balancing as of the 2021.09 release.

However, with replicas > 1 I'm running into some authentication issues:

```
2022-01-08T04:37:43.467818Z [rserver] ERROR system error 74 (Bad message) [description: error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error, description: Failed sign-in - unable to decrypt password - error]; OCCURRED AT rstudio::core::Error rstudio::core::system::crypto::rsaPrivateDecrypt(const string&, std::__cxx11::string*) src/cpp/core/system/Crypto.cpp:377; LOGGED FROM: void rstudio::server::pam_auth::{anonymous}::doSignIn(const rstudio::core::http::Request&, rstudio::core::http::Response*) src/cpp/server/ServerPAMAuth.cpp:134
```

When `replicas=1` I'm able to log in successfully.

it looks like the load-balancer file referenced in the [documentation](https://docs.rstudio.com/ide/server-pro/load_balancing/configuration.html#defining-nodes) isn't being created. The readme at `/etc/rstudio/README.md` in the container suggests that it should be located at `/mnt/load-balancer/rstudio/load-balancer`.

Is there a setting that I'm missing?

**Comment by d-m** [comment]
I just confirmed this is an issue with the missing `/mnt/load-balancer/rstudio/load-balancer` file.

I got it working by hacking together  a custom startup script to write the pod's IP address in the file:

```yaml
config:
  startupCustom:
    load-balancer.conf: |
      [program:load-balancer-file]
      command=/bin/sh -c "mkdir -p /mnt/load-balancer/rstudio && echo www-host-name=`hostname -i` > /mnt/load-balancer/rstudio/load-balancer && tail -f /dev/null"
```
