### ISSUE TITLE
PAM config files are executable

### ISSUE THREAD

**Issue by jaavalli** [rstudio/helm#141]
The file rstudio-workbench/templates/_helpers.tpl has following:

```
{{- if .Values.config.pam }}
- name: rstudio-pam
  configMap:
    name: {{ include "rstudio-workbench.fullname" . }}-pam
    defaultMode: 0755
```

So pam config files are set to executable. Shouldn't those files have something like 0644 permissions?
