### ISSUE TITLE
RStudio Connect: EFS Mount Issues - lchown operation not permitted 

### ISSUE THREAD

**Issue by RoyerRamirez** [rstudio/helm#142]
Hi,

I'm deploying RStudio Connect on EKS (Elastic Kubernetes Service). I'm using the sharedStorage option backed by EFS (Elastic File System).  The RStudio Connect deployment comes online.  The issue is when deploying apps, I keep seeing the following filesystem issues:

```
2022/01/14 20:31:32 POST to /__api__/applications/1/upload caused a non-API error: lchown /mnt/rs-connect/data/apps/1/1: operation not permitted
```

Helm Chart Version: 0.2.20

Helm Chart Values (I omitted some values like passwords, and other non relevant info like SMPT, Postgres details, etc...):
```
sharedStorage:
  create: true
  name: "rs-connect"
  mount: true
  path: /mnt/rs-connect/data 
  storageClassName: rs-connect
  accessModes:
    - ReadWriteMany
  requests:
    storage: "100Gi"

rbac:
  create: true
  clusterRoleCreate: true
  serviceAccount:
    create: true

extraObjects: []

image:
  repository: ghcr.io/rstudio/rstudio-connect
  tag: ""
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets: []

service:
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  type: LoadBalancer
  nodePort: false
  port: 80

pod:
  haste: true
  env: []
  serviceAccountName: false
  annotations: {}
  labels: {}
  sidecar: false
  command: []
  args: []
  replicas: 1

license:
  key: "XXX"
  server: false
  file:
    contents: false
    mountPath: "/etc/rstudio-licensing"
    mountSubPath: false
    secretKey: "license.lic"
    secret: false

securityContext: null

prometheusExporter:
  enabled: false

livenessProbe:
  enabled: false
  httpGet:
    path: /__ping__
    port: 3939
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 10

startupProbe:
  enabled: false
  httpGet:
    path: /__ping__
    port: 3939
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 30

readinessProbe:
  enabled: true
  httpGet:
    path: /__ping__
    port: 3939
  initialDelaySeconds: 3
  periodSeconds: 3
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

initContainers: false

ingress:
  enabled: false

launcher:
  enabled: true
  customRuntimeYaml: false
  launcherKubernetesProfilesConf: {}
  contentInitContainer:
    repository: ghcr.io/rstudio/rstudio-connect-content-init
    tag: ""

config:
  HTTP:
    Listen: :3939
  Authentication:
   Provider: password 
  Authorization:
    UserInfoEditableBy: AdminAndSelf
  Password: 
    SelfRegistration: true 
  Server:
    RVersionScanning: false
    RVersion: "/opt/R/4.1.1"
    TempDir: "/tmp"
    Address: http://localhost:3939 
    DataDir: "/mnt/rs-connect/data"
  Launcher:
    DataDir: "/mnt/rs-connect/data"
  Database:
    Provider: "Postgres"
    Dir: "/mnt/rs-connect/data"
```

**Comment by RoyerRamirez** [comment]
We can close the issue now. This issue was resolved by upgraded to the development EFS drivers that allowed me to specify guid and uid in the storageclass. It appears RStudio Connect is needing to use guid: 999 and uid: 999. 


Must have devevolpment drivers installed 
```
kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/dev/?ref=master"
```


Example StorageClass that fixed file permissions for me:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  name: rstudio-connect
parameters:
  basePath: /rstudio-connect
  fileSystemId: XXX
  gid: "999"
  provisioningMode: efs-ap
  uid: "999"
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by Almenon** [comment]
Rstudio connect now uses the root user (uid/gid 0). For me I was able to fix this by specifying uid/gid 0 in the storageclass, like so:

```yaml
# helm chart
{{- range .Values.efsStorageClasses }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .namePrefix | lower }}-efs"
parameters:
{{ .parameters | toYaml | indent 2 }}
provisioner: efs.csi.aws.com
---
{{- end }}

# values passed to helm chart
storage-classes:
  enabled: True
  efsStorageClasses:
    - namePrefix: posit-connect
      parameters:
        fileSystemId: fs-13d16515b57a3320d
        provisioningMode: efs-ap
        directoryPerms: "700"
        uid: "0"
        gid: "0"
```
