### ISSUE TITLE
Adding a sidecar to session pods via `job-json-overrides` prevents Workbench from connecting to session

### ISSUE THREAD

**Issue by d-m** [rstudio/helm#145]
We run node_exporter in user sessions to get additional metrics on session read/write behavior. We currently install it in each session container but would like to run it as a sidecar instead to simplify our images. When I added the following to the `json-job-overrides` section of the config:

```yaml
config:
  profiles:
    launcher.kubernetes.profiles.conf:
      "*":
        job-json-overrides:
          - target: /spec/template/spec/containers/1
            json:
              image: "quay.io/prometheus/node-exporter:v1.3.1"
              name: "node-exporter"
              command:
                - node_exporter
                - --collector.disable-defaults
                - --collector.mountstats
                - --web.disable-exporter-metrics
            name: nodeExporterSidecar
```

the sidecar is created and the pod starts. However, Workbench is unable to connect to the pod and reports the following error in `/var/log/rstudio/launcher/rstudio-kubernetes-launcher.log`:

```
2022-01-19T01:24:36.087036Z [rstudio-kubernetes-launcher] ERROR system error 71 (Protocol error) [description: watchPodLogs: received non-streaming response: Bad Request - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod session-34051cfc78a31b207e05e-USERNAME---rstudio-sessio--1-vblzj, choose one of: [5964456645756e31523730702b4b57455844483063773d3d node-exporter]","reason":"BadRequest","code":400}|||]; OCCURRED AT rstudio::job_launcher::impls::kubernetes::KubernetesApi::watchPodLogs(const string&, const OnLogOutputHandler&, const ErrorHandler&)::<lambda(const rstudio::core::http::Response&)> src/cpp/job_launcher/impls/kubernetes/KubernetesApi.cpp:1092; LOGGED FROM: rstudio::job_launcher::impls::kubernetes::KubernetesOutputStream::init()::<lambda(const rstudio::core::json::Array&)>::<lambda(const rstudio::core::Error&)> src/cpp/job_launcher/impls/kubernetes/KubernetesOutputStream.cpp:85
```

It looks like the Kubernetes Plugin assumes that there will only be one container per session pod. There's no issue with the Helm chart, so If this isn't the right venue for this error please let me know and I'll report it via support and our sales rep.
