### ISSUE TITLE
Specify `defaultMode` for session-scoped config files

### ISSUE THREAD

**Issue by d-m** [rstudio/helm#151]
Since the session-scoped configuration files ([`config.session.*`](https://github.com/rstudio/helm/blob/920b136037e29b7ec846a0d3021591eead497c0f/charts/rstudio-workbench/values.yaml#L279) in the `values.yaml`) are mounted on both the server and the sessions, we are using them to create an `entrypoint.sh` file on the sessions in order to override the entrypoint for sessions (background on the entrypoint requirements are [here](https://support.rstudio.com/hc/en-us/articles/360059743753-Customizing-the-Entrypoint-with-RStudio-Workbench-RStudio-Server-Pro-Job-Launcher-and-Kubernetes), thanks @colearendt):

```
config:
  session:
    entrypoint.sh: |
      #!/bin/bash

      set -xe

      # custom stuff here

      # Launch the session based on RSTUDIO_TYPE
      if [[ "$RSTUDIO_TYPE" == "session" ]]; then
        echo 'Starting RStudio session...'
        exec "/usr/lib/rstudio-server/bin/rserver-launcher" "$@"
      elif [[ "$RSTUDIO_TYPE" == "adhoc" ]]; then
        echo 'Starting RStudio ad hoc job...'
        /bin/bash "$@"
      else
        echo "ERROR: Unknown RSTUDIO_TYPE: $RSTUDIO_TYPE"
        exit 1
      fi
```

This mounts correctly in the session at `/mnt/session-configmap/rstudio/entrypoint.sh`, however it can't be used directly as the entrypoint as part of a [`config.profiles.*.*.job-json-overrides`](https://github.com/rstudio/helm/blob/920b136037e29b7ec846a0d3021591eead497c0f/charts/rstudio-workbench/values.yaml#L338) entry because it's not executable. To get around this, we've had to hack together a workaround to copy the script to a new location, make it executable, and call it:

```
config:
  profiles:
    launcher.kubernetes.profiles.conf:
      "*":
          - target: /spec/template/spec/containers/0/command
            json:
            - sh
            - -c
            - 'cp /mnt/session-configmap/rstudio/entrypoint.sh /bin/entrypoint.sh && chmod +x /bin/entrypoint.sh && /bin/entrypoint.sh $@'
            - sh
            name: commandOverride   
```

It would be helpful if we could pass in a [`defaultMode`](https://kubernetes.io/docs/concepts/configuration/secret/#secret-files-permissions) with [`config.session.*`](https://github.com/rstudio/helm/blob/920b136037e29b7ec846a0d3021591eead497c0f/charts/rstudio-workbench/values.yaml#L279) to mount this file as executable from the start, which would allow us to simplify the `job-json-override` to:

```
config:
  profiles:
    launcher.kubernetes.profiles.conf:
      "*":
          - target: /spec/template/spec/containers/0/command/0
            json: /mnt/session-configmap/rstudio/entrypoint.sh
            name: commandOverride   
```

This might be useful for session-scoped secrets and server-scoped configs and secrets as well, but our particular use-case is just the session-scoped config files.
