### ISSUE TITLE
RSW: OIDC auth with replica >=2

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#165]
When increasing replicas, we face issues with OIDC auth (which works fine with `replica = 1`):

```
2022-03-02T15:37:10.117201Z [rserver] ERROR OpenID failed with error: attempt to use invalid state: 041fc65df50a6e8b7390213efac495b3f125b9e1d8b43df1b1df8c9b163da162; LOGGED FROM: void rstudio::server::openid_auth::{anonymous}::writeResponse(rstudio_boost::shared_ptr<rstudio::core::http::AsyncConnection>, const rstudio::core::http::Response&) src/cpp/server/openid_auth/ServerOpenIDAuth.cpp:145
```

We're using a Postgres DB and besides the DB settings we have set

```yml
config:
  server:
    rserver.conf:
      server-shared-storage-path: /home/shared-storage
secureCookieKey: <some key>

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotation:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "RSW-SESSION-COOKIE"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
```

Is there anything additional which needs to be configured to get OIDC auth working in HA configuration?
