### ISSUE TITLE
RSW: instructions for configuring rJava support

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#190]
Following up from a discussion with RStudio support, it would be helpful to have instructions for configuring rJava support in RSW sessions.

[This RStudio support article](https://support.rstudio.com/hc/en-us/articles/360058209074-Using-rJava-with-RStudio-Workbench-RStudio-Server-Pro-Launcher-and-Kubernetes) is a good starting point but gets a bit confusing at the end and it is not fully clear if local image modications are needed or which config setting is required, especially when using the helm chart.

Currently it seems that one must configure `config.session.r-versions` verbatim with the following to get a correct `LD_LIBRARY_PATH` within the session images:

```yml
config:
  session:
    r-versions: |
      Path: /opt/R/4.2.0
      Script: /opt/R/4.2.0/lib/R/etc/ldpaths

      Path: /opt/R/4.1.3
      Script: /opt/R/4.1.3/lib/R/etc/ldpaths

      [...]
```

(credits to Lachlan)
