### ISSUE TITLE
'nodeSelector' for rstudio-connect helm

### ISSUE THREAD

**Issue by jonlinca** [rstudio/helm#192]
In our current RStudio Connect K8s environment, we have two nodes - one 'main' node intended for rstudio-connect deployment (nfs, ingress, database and main app), and one 'content' node for the content pods.

We can successfully target the content pods to go into the content node, so no worries there. However, we just ran into a situation where we did a `helm upgrade ` and the main rstudio-connect deployment got re-deployed into the content node, versus the main node that we expected.

We would like to avoid this in the future. Would we need to update the rstudio-connect helm chart to allow the 'main app' deployment to target a node via nodeSelector, or is it possible with the current helm chart version?

**Comment by jonlinca** [comment]
I think we managed to solve the problem by using affinities instead, which exist in the current helm chart. 
```
pod:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: rsc
              operator: In
              values:
              - main
```
Apologies for the noise.
