### ISSUE TITLE
nodeSelector and affinity consistency

### ISSUE THREAD

**Issue by colearendt** [rstudio/helm#223]
The charts are currently all over the place with consistency on affinity and nodeSelectors

Related to #17 and #192

**Comment by rodrigobrim** [comment]
The values.yaml/docs does not have any reference to the [selectorLabels](https://github.com/rstudio/helm/blob/b878e60519b56d357d421041f87de214faab0da6/charts/rstudio-pm/templates/deployment.yaml#L18) config.

**Comment by dbkegley** [comment]
Another thing to note: tolerations are also handled differently. RSW appears to support a top-level `tolerations` field, while the Connect chart does not yet support tolerations. It would be great to consolidate these into a single approach or use a library helper for some of these common configurations files on the top-level `pod`

**Comment by pat-s** [comment]
Unfortunately we're still facing placement issues on our mixed arch cluster: we have set 

```yml
config:
  profiles:
    launcher.kubernetes.profiles.conf:
       "*":
         placement-constraints: "kubernetes.io/arch=amd64"
```

and we see 

![image](https://user-images.githubusercontent.com/8430564/222502784-420cdb79-66c8-4a97-9fb8-6105f529b501.png)

yet sessions still get scheduled on the arm64 nodes from time to time.

I double-checked that the entry is reflected correctly into `/mnt/configmap/rstudio/launcher.kubernetes.profiles.conf` in the WB server pod:

```
[*]
placement-constraints=kubernetes.io/arch=amd64
```

Is there anything I am still misconfiguring here? 🤔

**Comment by colearendt** [comment]
I think the way you want to set these are:
```
config:
  profiles:
    launcher.kubernetes.profiles.conf:
       "*":
         placement-constraints: 
           - "kubernetes.io/arch:amd64"
```

But it will only allow selection of amd64 - default will still be to not specify a placement constraint 😞
