### ISSUE TITLE
Launcher SSL

### ISSUE THREAD

**Issue by roberts2727** [rstudio/helm#226]
We are working on a deployment where all three products will be running on one single Kubernetes Cluster, I am having a bit of a hard time getting launcher to work with SSL. In our launcher.conf file and rserver.conf files, should we be specifying localhost as the Launcher address?

address=localhost
port=5559

or should it be our workbench url

address=workbench.domain.com
port=5559

and for the SSL Cert, does it need to be issued to localhost?

**Comment by colearendt** [comment]
Hello @roberts2727 ! This is a fantastic question! This will depend a bit on your setup. If it is possible to issue your SSL cert for localhost, then you can definitely use the `localhost` address. This will mean that traffic for _each_ workbench pod will communicate with launcher over loopback within its own container.

There are some other options, but it is unlikely that `workbench.domain.com` will work since we [do not expose launcher as its own service](https://github.com/rstudio/helm/blob/main/charts/rstudio-workbench/templates/svc.yaml) 😞 I definitely think we have a bit of work to do here to make the SSL story a bit cleaner, provide [examples](https://github.com/rstudio/helm/tree/main/examples), etc.

**Comment by colearendt** [comment]
I am hoping to get into reproducing this issue more intimately sometime soonish (related to #234 too).

However, in the meantime I took a glance at what we do for RStudio Connect (which currently manages launcher directly). What we do there is set the following settings to work with a self-signed certificate:

_launcher.conf_
```
enable-ssl=1
certificate-file=/path/to/cert.crt
certificate-key-file=/path/to/key.key
```

Documentation for the settings is [here](https://docs.rstudio.com/job-launcher/index.html#general-config). I suspect the problem is with the RStudio Workbench process not trusting the certificate. However, if you add the self-created CA to the server's trust store, then I would expect Workbench to pick that up (provided that `127.0.0.1` and/or `localhost` are in the certificate's SANs). 

These settings might be useful inside of `rserver.conf` though
_rserver.conf_
```
launcher-use-ssl=1
# if not in the trust store, need to turn off ssl verification
launcher-verify-ssl-certs=0
```
https://docs.rstudio.com/ide/server-pro/rstudio_server_configuration/rserver_conf.html#launcher-use-ssl

For the record, we do address to 127.0.0.1 by default. 

https://github.com/rstudio/helm/blob/72f5c8344a9cc9a3a8b080e4951b51b54e4e6195/charts/rstudio-workbench/values.yaml#L337

So altogether, I would expect this to be successful - converted to values:

```
config:
  server:
    launcher.conf:
      address: 127.0.0.1             # this is an IP interface to listen on, not a hostname
      enable-ssl: 1
      certificate-file: /path/to/cert.crt
      certificate-key-file: /path/to/key.key
    rserver.conf:
      launcher-use-ssl: 1
      launcher-verify-ssl-certs: 0
      launcher-address: 127.0.0.1     # should go over loopback, if you can add 127.0.0.1 as a SAN. Can also be a hostname
```
