### ISSUE TITLE
Ingress handle undefined paths?

### ISSUE THREAD

**Issue by colearendt** [rstudio/helm#240]
Related to #52 

Should we handle undefined `paths` like:
```
ingress:
  enabled: true
  hosts: 
    - host: myhost.com
```
