### ISSUE TITLE
RSW: Tolerations and affinity for session pods

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#271]
Azure SPOT instances require setting certain affinity and tolerations for a pod to be able to scheduled on it. See https://docs.microsoft.com/en-us/azure/aks/spot-node-pool#verify-the-spot-node-pool.

Here's the required config:

```yml
  tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "kubernetes.azure.com/scalesetpriority"
            operator: In
            values:
            - "spot"
```

AFAICS one can currently only define these for the server pods (which then get scheduled fine). Session pods error with

```
Warning  FailedScheduling  5m33s  default-scheduler  0/2 nodes are available: 1 Insufficient memory, 1 node(s) had untolerated taint {kubernetes.azure.com/scalesetpriority: spot}.
```
