### ISSUE TITLE
PM unable to initialize configuration

### ISSUE THREAD

**Issue by smokedlinq** [rstudio/helm#287]
Trying to deploy package manager with sharedStorage against an azurefile-csi-premium storage class. Receiving the error while pods are started:

`cannot chown /var/lib/rstudio-pm/launcher_internal/rstudio-pm-c57cbcf88-5kmgx/secure-cookie-key to 0600: chmod /var/lib/rstudio-pm/launcher_internal/rstudio-pm-c57cbcf88-5kmgx/secure-cookie-key: operation not permitted`

Configuration values:

```yaml
sharedStorage:
  create: true
  mount: true
  storageClassName: rstudio-pm-azurefile-csi-premium
  requests:
    storage: 100Gi

extraObjects:
  - |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: rstudio-pm-azurefile-csi-premium
    provisioner: file.csi.azure.com
    allowVolumeExpansion: true
    parameters:
      skuName: Premium_LRS
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    mountOptions:
      - mfsymlinks
      - actimeo=30
```

I tried adding `dir_mode` and `file_mode` to the mountOptions like what is required in Connect, but that didn't work either.
