### ISSUE TITLE
Add securityContext to templating

### ISSUE THREAD

**Issue by colearendt** [rstudio/helm#293]
This is an important miss 😞

**Comment by pat-s** [comment]
I think I am right now stumbling over this.

On AKS with a policy denying priviliged execution, I am struggling to set the `securityContext` of the `packrat-restore` job.batch to `null`. By default it is set to 

```yml
securityContext:                                                          
  runAsGroup: 999                                                         
  runAsUser: 999
```

which results in a denied execution by the gatekeeper.

Setting

```yml
launcher:
  useTemplates: true
  enabled: true
  templateValues:
    job:
      securityContext: null
```

doesn't change yet.

**Comment by pat-s** [comment]
AFAICS the job definition of `securityContext` is currently not accepting templateData input:

https://github.com/rstudio/helm/blob/9d58e030b0eafac5a4834a131685d62dd1c9d0c5/charts/rstudio-connect/files/job.tpl#L111-L115

**Comment by colearendt** [comment]
Howdy @pat-s! Thanks for the practical example here! Can I ask what error message the gatekeeper is throwing? I am surprised that it is upset about `runAsUser` and `runAsGroup` - that is an important piece of defining an unprivileged job in my understanding 😮  (it is basically saying: make sure you don't run this as root. Instead use uid/gid 999/999)

**Comment by pat-s** [comment]
Apologies for making rookie mistakes here, this is the first time I am doing such a deep dive on the non-root executions 🙃 

The gatekeeper throws

```
{"level":"info","ts":1669115646.2458007,"logger":"webhook","msg":"denied admission","process":"admission","event_type":"violation","constraint_name":"azurepolicy-k8 │
│ sazurev3noprivilegeescalatio-11f7b53155b7de191e38","constraint_group":"constraints.gatekeeper.sh","constraint_api_version":"v1beta1","constraint_kind":"K8sAzureV3No │
│ PrivilegeEscalation","constraint_action":"dryrun","resource_group":"","resource_api_version":"v1","resource_kind":"Pod","resource_namespace":"connect","resource_nam │
│ e":"run-shiny-application-vcr6c-jjz7q","request_username":"system:serviceaccount:kube-system:job-controller"}
```

The `job.batch` itself is running with

```yml
securityContext:                                                          
  runAsGroup: 999                                                         
  runAsUser: 999  
```

so actually this shouldn't be the issue then. Why do I think the gatekeeper targets the `job.batch` definition? -> these never get to start a pod in the first place (always at `0/1`), so I think the gatekeeper denies at this level.

The definition is defined here: https://store.policy.core.windows.net/kubernetes/container-no-privilege-escalation/v3/template.yaml

I am not sure if I read it correctly but does the following part of the definition maybe mean "escalate if `runAsUser` is not 0 and allowPrivilegeEscalation is not set to false"?

```
        input_allow_privilege_escalation(c) {
            not c.securityContext.allowPrivilegeEscalation == false
            c.securityContext.runAsUser != 0
        }
```

I will dive in a bit more today to get a better understanding what the policy expects as this is currently a blocker in one of our ongoing installations and I don't see connect getting whitelisted for that policy in the short and longterm. 

You help is highly appreciated!

**Comment by colearendt** [comment]
This is really interesting! So much for "dryrun" 🤣 

This is interesting though - I was not familiar with the GateKeeperPolicyAgent: https://github.com/open-policy-agent/gatekeeper

It looks to me like the problem that this is encountering is that we have unspecified `allowPrivilegeEscalation`, so (1) either the default is `true` or the fact that it is not `== false` (i.e. unset) is causing the failure. I have an idea that may make it possible to tweak this that shouldn't be too tricky to implement.

**Comment by pat-s** [comment]
I've tried changing `securityContext` in a few places but didn't succeed yet. 
Just to share my actions: When setting the following in `values.yml`

```yml
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser: 999
  runAsGroup: 999
```

the initial Connect pod fails to start with `mkdir: cannot create directory ‘/mnt/dynamic’: Permission denied`. Setting `securityContext: null` works. Does the initial connect pod still need root privileges at least for the volume mounts?

I haven't succeeded changing the `securityContext` for the job definition (yet) as `allowPrivilegeEscalation` is always reported as an "unknown field", probably because it hasn't been defined previously in another place (in the deployment?).
