### ISSUE TITLE
Issue with launcher templates

### ISSUE THREAD

**Issue by pmaterer** [rstudio/helm#295]
I'm trying to have my session pods use a specific service account (with an IRSA role).

I believe the way to do this is set it in `launcher.templateValues.pod.serviceAccoutName` (and have `launcher.useTemplates = true`)?

Here is are my values:

```
USER-SUPPLIED VALUES:
config:
  pam:
    common-session: |
      session [default=1] pam_permit.so
      session requisite   pam_deny.so
      session required    pam_permit.so
      session optional    pam_umask.so
      session required    pam_unix.so
    rstudio-session: |
      auth       sufficient pam_rootok.so
      auth       optional   pam_group.so
      session    required   pam_mkhomedir.so skel=/etc/skel/ umask=0022
      session    required   pam_env.so readenv=1 envfile=/etc/default/locale
      session    required   pam_limits.so
      session    optional   pam_sss.so
      @include common-auth
      @include common-account
      @include common-session
  profiles:
    launcher.kubernetes.profiles.conf:
      '*':
        allow-unknown-images: 0
        container-images: [redacted] # based on rstudio/r-session-complete:bionic-2022.07.1-554.pro3
        default-container-image: [redacted] # based on rstudio/r-session-complete:bionic-2022.07.1-554.pro3
        default-cpus: 1
        default-mem-mb: 8096
        max-cpus: 32
        max-mem-mb: 131072
    profiles:
      '*':
        session-limit: 4
  server:
    jupyter.conf:
      default-session-cluster: Kubernetes
      jupyter-exe: /usr/local/bin/jupyter
      labs-enabled: 1
      notebooks-enabled: 1
      session-cull-connected: 0
      session-cull-minutes: 540
      session-shutdown-minutes: 0
    launcher.conf:
      cluster:
        name: Kubernetes
        type: Kubernetes
    logging.conf:
      '*':
        log-level: info
        logger-type: stderr
    rserver.conf:
      admin-enabled: 1
      admin-superuser-group: rstudio-admins
      auth-pam-sessions-enabled: 1
      auth-pam-sessions-profile: rstudio-session
      auth-saml: 1
      auth-saml-metadata-url: [redacted]
      auth-saml-sp-attribute-username: NameID
      auth-saml-sp-base-uri: [redacted]
      launcher-address: 127.0.0.1
      launcher-default-cluster: Kubernetes
      launcher-port: 5559
      launcher-sessions-create-container-user: 1
      launcher-sessions-enabled: 1
      monitor-graphite-enabled: 0
      rsession-which-r: /opt/R/4.1.0/bin/R
      server-health-check-enabled: 1
      server-project-sharing: 1
      server-shared-storage-path: /home/shared-storage
      session-ssl-verify-certs: 0
      www-allow-origin:
      - [redacted]
      - [redacted]
      www-enable-origin-check: 1
      www-port: 8787
    vscode-user-settings.json: |
      {
        "extensions.autoCheckUpdates": true,
        "extensions.autoUpdate": true,
        "terminal.integrated.shell.linux": "/bin/bash"
      }
    vscode.conf:
      args: --verbose --host=0.0.0.0
      enabled: 1
      exe: /opt/code-server/bin/code-server
  startupUserProvisioning:
    sssd.conf: |
      [program:sssd]
      autorestart=false
      command=[redacted]
      numprocs=1
      redirect_stderr=true
      stdout_logfile=/var/log/sssd/sssd.log
  userProvisioning:
    [redacted]
homeStorage:
  create: true
  mount: true
  name: rstudio-workbench-home
  requests:
    storage: 50Gi
  storageClassName: efs-rstudio-workbench
image:
  repository: [redacted] # based on rstudio/rstudio-workbench:bionic-2022.07.1-554.pro3
  tag: 0.2.0-bionic-2022.07.1-554.pro3
ingress:
  [redacted]
launcher:
  templateValues:
    pod:
      serviceAccountName: rstudio-workbench-session
  useTemplates: true
launcherPem: |
  [redacted]
launcherPub: |
  [redacted]
license:
  server: [redacted]
pod:
  env:
  - name: ACTIVE_DIRECTORY_PASSWORD
    value: [redacted]
rbac:
  clusterRoleCreate: true
secureCookieKey: [redacted]
session:
  rsession.conf:
    allow-file-downloads: 0
    r-cran-repos: [redacted]
    restrict-directory-view: 1
    session-save-action-default: false
strategy:
  type: Recreate
```

When I try to launch a session:

```
2022-11-07T19:44:13.915083Z [rstudio-kubernetes-launcher, log-source: Kubernetes] ERROR system error 71 (Protocol error) [description: Invalid status returned from create resource at /apis/batch/v1/namespaces/rstudio-workbench/jobs: Bad Request - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the object provided is unrecognized (must be of type Job): yaml: line 34: could not find expected ':' (232056657273696f6e3a20320a2320444f204e4f54204d4f444946592074 ...)","reason":"BadRequest","code":400}
2022-11-07T19:44:13.915484Z [rserver] ERROR system error 71 (Protocol error) [description: The Launcher is not properly configured. Please contact your system administrator., details: Invalid launcher response: {"errorCode":0,"message":"Kubernetes API failure"}, http status code: 500]; OCCURRED AT rstudio::server::job_launcher::rpc::{anonymous}::launchSession(const string&, rstudio_boost::shared_ptr<rstudio::core::http::AsyncConnection>)::<lambda(const rstudio::core::http::Response&)> src/cpp/server/ServerJobLauncherRpc.cpp:311; LOGGED FROM: rstudio::server::job_launcher::rpc::{anonymous}::launchSession(const string&, rstudio_boost::shared_ptr<rstudio::core::http::AsyncConnection>)::<lambda(const rstudio::core::http::Response&)> src/cpp/server/ServerJobLauncherRpc.cpp:317
```
