### ISSUE TITLE
is it possible to run Julia content on RSC

### ISSUE THREAD

**Issue by airpaio** [rstudio/helm#303]
In Workbench I have a custom image with Julia installed that developers can work with in their VS Code sessions.

I am wondering if/how it might be possible to run Julia stuff on Connect? Perhaps with Scheduled content? 
Disclaimer - I'm not a Julia developer. I'm just setting up infra for trial license evaluation of the RStudio Team platform. Julia capabilities was just aa request from our users, but I'm not sure how Julia content could be published and run on RSC's Launcher.

In rstudio-connect values.yml could this be a valid `additionalRuntimeImages` with julia?

```yaml
additionalRuntimeImages: |
    - name: my-repo/image-with-python-r-julia:2022.11.18
      python:
        installations:
          - path: /opt/python/3.9.5/bin/python3.9cd
            version: 3.9.5
      r:
        installations:
          - path: /opt/R/4.1.0/bin/R
            version: 4.1.0
      julia:
        installations:
          - path: /opt/julia-1.8.2/bin/julia
            version: 1.8.2
```
