### ISSUE TITLE
Connect: allow specifying resources in templates

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#306]
Motivation: AKS has some `azure-policies` in place which deny spawning pods without a resource definition. This applies to the `packrat-restore` pods and eventually denies app deployment.

`values.yml`:

```yml
  templateValues:
    service:
      type: ClusterIP
      annotations: {}
      labels: {}
    pod:
      annotations: {}
      labels: {}
      serviceAccountName: ""
      volumes: []
      volumeMounts: []
      imagePullPolicy: ""
      imagePullSecrets: []
      initContainers: []
      extraContainers: []
      resources: {} # <---- NEW
```

As a workaround I am currently trying with

```yml
launcher:
  enabled: true
  useTemplates: false
  launcherKubernetesProfilesConf:
    "*":
      job-json-overrides:
        - name: resources
          target: /spec/template/spec/containers/resources
          json:
            requests:
              cpu: "100m"
              memory: "200Mi"
              ephemeral-storage: "200Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
              ephemeral-storage: "2Gi"
```

but this specification results in a 500 from the launcher.

**Comment by colearendt** [comment]
Howdy @pat-s ! Thanks for sending this along!

We actually have a slightly more native option for configuring `resources` today. 

```
launcher:
  launcherKubernetesProfilesConf:
    "*":
      default-cpu: 2
      default-mem-mb: 2048
      cpu-request-ratio: 0.1
      memory-request-ratio: 0.2
```

https://docs.posit.co/job-launcher/kube.html#kube-profiles

Unfortunately this is global and not specified per content. We are shooting for an even-more-native implementation which will allow users to specify resources inside of the UI similar to "number of processes", "connection timeouts," etc. This will allow varying resource selection per content item using the API.

If you have any feedback on whether you would expect this resource-permission selection to be set by publishers or admins-only, or what mechanics would be ideal (i.e. a default value, and users can override, etc.), that would be most welcome!
