### ISSUE TITLE
Create an ArtifactHub-friendly ChangeLog

### ISSUE THREAD

**Issue by colearendt** [rstudio/helm#34]
We already have a `NEWS.md` in each chart that is human-readable

Artifact Hub has a notion of putting a changelog inside of the `Chart.yaml` to tell about changes for a particular release

_Chart.yaml_
```
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add Artifact Hub CLI tool
    - kind: added
      description: Add support for Keptn integrations
    - kind: added
      description: Search results can now be sorted by relevance or stars
    - kind: added
      description: Allow users deleting their accounts
    - kind: added
      description: Allow users cropping their avatar image
    - kind: changed
      description: Related packages are now displayed below the readme in some cases
    - kind: changed
      description: Use third party library for readme ToC generation
    - kind: changed
      description: Bump Alpine to 3.14
    - kind: changed
      description: Bump Trivy to 0.19.2
      links:
        - name: Trivy migrating to new JSON schema
          url: https://github.com/artifacthub/hub/pull/1437#issue-689445316
    - kind: changed
      description: Bump OPM to 1.17.5
    - kind: changed
      description: Upgrade backend dependencies
    - kind: changed
      description: Upgrade frontend dependencies
    - kind: fixed
      description: Some bugs and other improvements
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: db-migrator
      image: artifacthub/db-migrator:v1.1.0
    - name: hub
      image: artifacthub/hub:v1.1.0
    - name: tracker
      image: artifacthub/tracker:v1.1.0
    - name: scanner
      image: artifacthub/scanner:v1.1.0
    - name: trivy
      image: aquasec/trivy:0.19.2
apiVersion: v2
appVersion: 1.1.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.helm.sh/stable
  version: 8.2.1
description: Artifact Hub is a web-based application that enables finding, installing,
  and publishing Kubernetes packages.
home: https://artifacthub.io
icon: https://artifacthub.github.io/helm-charts/logo.png
keywords:
- kubernetes
- helm
- falco
- opa
- olm
- tinkerbell actions
- krew
- tekton
- keda scalers
- coredns
- keptn
kubeVersion: '>= 1.14.0-0'
maintainers:
- email: tegioz@icloud.com
  name: Sergio
- email: cynthiasg@icloud.com
  name: Cintia
- email: matt@mattfarina.com
  name: Matt
name: artifact-hub
type: application
version: 1.1.0
```

An example of how it is displayed in ArtifactHub is here: https://artifacthub.io/packages/helm/artifact-hub/artifact-hub

- [ ] Find a way to maintain only 1 "source of truth" and code-generate the other, so that they stay in sync
- [ ] Set up the annotations in Chart.yaml
- [ ] Publish the chart and verify that the annotations show up in ArtifactHub
