### ISSUE TITLE
Clarify that Connect with off-host execution requires a PV and  PVC

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/helm#341]
https://github.com/rstudio/helm/blob/c48d94fda4562795ca9010f334c2c11271a8073f/charts/rstudio-connect/README.md?plain=1#L48-L54

**Comment by kevinchiang** [comment]
I think it would be useful to provide an example for the second bullet point.  Including which path(s) the volumeMounts need to be mounted

```
# Configures shared storage for the RStudio Connect pod.
# sharedStorage:
#   create: false
#   mount: false
#   accessModes: ["ReadWriteMany"]
#   volumeName: rstudio-connect-pv

#   # The name of the PVC that will be created for Connect's data directory.
#   # This PVC is also specified by `Launcher.DataDirPVCName` below.
#   name: rstudio-connect-pvc


# Enables building and executing content in isolated Kubernetes pods.
launcher:
  enabled: true
  defaultInitContainer:
    enabled: true
    repository: --private-registry-omitted--/artifactory/api/docker/ghcr-io-docker-remote/rstudio/rstudio-connect-content-init
    tagPrefix: bionic-
  templateValues:
    pod:
      imagePullPolicy: Always
      imagePullSecrets:
        - name: regsecret
      volume:
        - name: rsc-volume
          nfs:
            server: --omitted--
            path: /rstudio_connect
      volumeMounts:
        - mountPath: /opt/rstudio-connect
          name: rsc-volume
        - mountPath: /mnt/rstudio-connect-runtime
          name: rsc-volume
```

trying to deploy a chart on 0.4.2 results in the following error message:
```
Error: execution error at (rstudio-connect/templates/NOTES.txt:46:6):

When launcher is enabled, persistent storage must be provided.
This is usually done via a PersistentVolumeClaim (PVC) with `sharedStorage.create=true`, although there are other options.
```
