### ISSUE TITLE
Is `config.sessionCustomStartup` possible on Workbench?

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/helm#344]
The Workbench Helm chart currently has a `config.customStartup` key. For example:

https://github.com/rstudio/helm/blob/c48d94fda4562795ca9010f334c2c11271a8073f/examples/auto-scaling/rstudio-workbench/values.yaml#L148-L162

Would it be possible to have scripts that run when a IDE session starts? The motivation for this is a want to create a symlink on the session container before the IDE starts. For example:

```yaml
config:
  session:
    repos.conf:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      CRAN: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
  sessionCustomStartup:
    symlink-odbc.sh: |
      #!/bin/bash
      ln -s /mnt/session-secret/odbc.ini /ect/odbc.ini
  sessionSecret:
    odbc.ini: |
      [ProjectAbcDatabase]
      Database=project_abc
      Driver=PostgreSQL
      Password=password
      Port=5432
      Servername=database-postgresql
      UserName=posit_team
```

Or maybe there is a way to already do this?
