### ISSUE TITLE
Workbench helm chart is sorting `config.profiles.launcher.kubernetes.profiles.conf`

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/helm#346]
Workbench helm chart is sorting `config.profiles.launcher.kubernetes.profiles.conf`. This is not desired behaviour because the order of the configuration matters. For example:

```yaml
# values.yaml
config:
  profiles:
    launcher.kubernetes.profiles.conf:
      "*":
        default-cpus: 1
        default-mem-mb: 1024
      "@group2":
        default-cpus: 1
        default-mem-mb: 1024
      "@group1":
        default-cpus: 1
        default-mem-mb: 1024
```

In the template, the order of "group1" and "group2" are reversed.

```bash
$ helm template my-deployment rstudio/rstudio-workbench -f values.yaml | grep "launcher.kubernetes.profiles.conf" -A 21

  launcher.kubernetes.profiles.conf: |
  
    [*]
    allow-unknown-images=1
    container-images=rstudio/r-session-complete:bionic-2022.12.0
    default-container-image=rstudio/r-session-complete:bionic-2022.12.0
    default-cpus=1
    default-mem-mb=1024
    job-json-overrides="/spec/template/spec/volumes/-":"/mnt/job-json-overrides-new/defaultSessionVolume.json","/spec/template/spec/containers/0/volumeMounts/-":"/mnt/job-json-overrides-new/defaultSessionVolumeMount.json"
  
    [@group1]
    default-cpus=1
    default-mem-mb=1024
  
    [@group2]
    default-cpus=1
    default-mem-mb=1024
```

Is there a way to prevent this from happening?
