### ISSUE TITLE
Package Manager - unable to find R

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/helm#365]
This is related to https://github.com/rstudio/rstudio-docker-products/issues/523. We will likely need to:

- Update the docker image to use R 3.6.2 as the helm chart expects
- Update the default value in the helm chart to use R 4.2.0

**Comment by colearendt** [comment]
#371 is related, but we actually fixed by putting 2 R versions into the RSPM container (for now). We are planning on fixing future references by symlinking to a common local path.

**Comment by bdeitte** [comment]
@SamEdwardes Going back through some issues as I can here... I'm assuming this is fixed now or is there something still here very broken?

**Comment by SamEdwardes** [comment]
Hi Brian, thanks for following up. I checked the following:

- I checked https://github.com/rstudio/rstudio-docker-products/issues/523. I was able to close this issue because the default config no longer causes an error on startup.
- Check the current `config` in values.yaml: https://github.com/rstudio/helm/blob/654400d0155e26e416781819e6c41564d99bc409/charts/rstudio-pm/values.yaml#L238-L243. Verified that it does not change anything related to Server.RVersion.
- Deployed the latest chart for PPM with the following values:

```yaml
replicas: 1

fullnameOverride: posit-package-manager

image:
  tagPrefix: jammy-

service:
  type: ClusterIP

sharedStorage:
  create: true
  mount: true
  name: posit-package-manager-pvc
  storageClassName: fsx-sc
  requests:
    storage: 1Gi
  annotations:
    helm.sh/resource-policy: null

config:
  Server:
    Address: https://ppm.example.org
  Authentication:
    APITokenAuth: true
  Database:
    Provider: postgres
  Postgres:
    URL: <redacted>
```

Verified that everything worked as expected. The config in my values.yaml completely override the config in the container (which is a good thing I think).

I think there is still opportunity to improve the image (e.g. why have two versions of R and Python). But that can be addressed in other issues. I will close this issue.
