### ISSUE TITLE
Add first class support for `/etc/pip.conf` in the values.yaml for Workbench and Connect

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/helm#369]
It is a common task for admins to customize pip settings, particularly the `index-url`. 

### Option 1 - first-class support

For example:

**Workbench**

```yaml
# values.yaml
config:
  session:
    repos.conf:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      CRAN: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
    # pip.conf should be written to /etc/pip.conf
    pip.conf: |
        [global]
        index-url = https://pypi.org/simple
```

**Connect**

I am less sure on what the correct approach for Connect should be, since current `config` key in the values.yaml maps directly to Connect config file.

### Option 2 - document examples

**Workbench**

```yaml
# values.yaml
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pip-config-workbench
    data:
      pip.conf: |
        [global]
        index-url = https://pypi.org/simple

launcher:
  enabled: true
  useTemplates: true
  templateValues:
    pod:
      volumes:
        - name: pip-config-volume
          configMap:
            name: pip-config-workbench
      volumeMounts:
        - mountPath: /etc/pip.conf
          name: pip-config-volume
          subPath: pip.conf
```

**Connect**

```yaml
# values.yaml
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pip-config-connect
    data:
      pip.conf: |
        [global]
        index-url = https://pypi.org/simple

launcher:
  enabled: true
  useTemplates: true
  templateValues:
    pod:
      volumes:
        - name: pip-config-volume
          configMap:
            name: pip-config-connect
      volumeMounts:
        - mountPath: /etc/pip.conf
          name: pip-config-volume
          subPath: pip.conf
```
