### ISSUE TITLE
workbench launcher.kubernetes.profiles.conf order in yaml doesn't matter, in configuration file its in alphabetical order

### ISSUE THREAD

**Issue by samssann** [rstudio/helm#415]
In my `values.yaml` file I have the following configuration:
```yaml
  profiles:
    launcher.kubernetes.profiles.conf:
      "*":
        allow-unknown-images: 0
        allow-custom-resources: 0
        resource-profiles: small
      "@rsw_user":
        resource-profiles: small
        allow-unknown-images: 0
      "@rsw_power":
        resource-profiles: small,power
        allow-unknown-images: 0
      "@rsw_advanced":
        resource-profiles: small,power,advanced
        allow-unknown-images: 1
        allow-custom-resources: 1
```
If i've understood correctly, the basic idea is that these configurations are iterated from top to bottom, so that the configurations in bottom override configurations in the top. say a user belongs to group rsw_user and rsw_advanced. this way the user should have the permissions defined in rsw_advanced. somehow however, the configuration file which is passed on to the workbench pod via configmap gets sorted in alphabetical order. meaning that in the configuration file, the order becomes: *, rsw_advanced, rsw_power, rsw_user.
