### ISSUE TITLE
Add documentation about setting r-versions in Workbench

### ISSUE THREAD

**Issue by tnederlof** [rstudio/helm#437]
Some customers need to set the `r-versions` config file to customize certain R version sessions as [documented here](https://docs.posit.co/ide/server-pro/r/using_multiple_versions_of_r.html#extended-r-version-definitions).

Nothing in the README mentions it but it is possible to customize as it is a file that just needs to make its way into the `/mnt/session-configmap/rstudio` directory. It is a tricky format that is not like the rest of Workbench config files so it needs to be in a form like the following in a `values.yaml` file:

```
config:  
  session:
    r-versions: |
        Path: /opt/R/4.1.3
        Label: Custom 4.1.3
        Repo: https://packagemanager.posit.co/cran/__linux__/jammy/latest

        Path: /opt/R/4.2.3
        Label: Custom 4.2.3
        Repo: https://p3m.dev/cran/__linux__/jammy/latest
```
