### ISSUE TITLE
Chronicle README Workbench example fixes

### ISSUE THREAD

**Issue by tnederlof** [rstudio/helm#445]
The chronicle helm chart README for Workbench has 
```
pod:
  sidecar:
    - name: chronicle-agent
      image: posit-chronicle:2023.11.3
      volumeMounts:
      - name: CHRONICLE_PRODUCT_CLUSTER_ID
        value: "posit-cluster-1"
      - name: logs
        mountPath: "/var/lib/rstudio-server/audit"
      env:
      - name: CHRONICLE_SERVER_ADDRESS
        value: "http://chronicle-server.default.svc.cluster.local"
```

This section is invalid as `volumeMounts` doesn't take a value. Perhaps it needs to be under `env` like in the Connect example.
```
      volumeMounts:
      - name: CHRONICLE_PRODUCT_CLUSTER_ID
        value: "posit-cluster-1"
```

Also, perhaps describe the purpose of `CHRONICLE_PRODUCT_CLUSTER_ID` if it's even needed?

Additionally, this example does not work without adding:
```
  volumes:
    - name: logs
      emptyDir: {}
  volumeMounts:
    - name: logs
      mountPath: "/var/lib/rstudio-server/audit"
```
