### ISSUE TITLE
Update the default Package Manager config to take advantage of R and Python autodetection

### ISSUE THREAD

**Issue by SamEdwardes** [rstudio/helm#473]
The current Package Manager docker image and helm chart have hard-coded R and Python configurations.

## Related

- https://github.com/rstudio/rstudio-docker-products/issues/523

## The issue

**Docker**

https://github.com/rstudio/rstudio-docker-products/blob/e0fa3ab39e64e6e9b03febcbcb97e71a96210596/package-manager/rstudio-pm.gcfg#L12-L14

```docker
; Git sources require a configured R installation. R is often installed at `/usr/lib/R`
; or `/usr/lib64/R`.
RVersion = /opt/R/default/
```

**Helm**

```yaml
# -- config is a nested map of maps that generates the rstudio-pm.gcfg file
config:
  Server:
    RVersion: "/opt/R/3.6.2/"
  HTTP:
    Listen: :4242
  Metrics:
    Enabled: true
```

Hard coding these values can lead to errors when starting Package Manager. In particular, this is an issue with hard coding the value into Helm because there is no guarantee that `/opt/R/3.6.2/` is installed.

## Proposed fix

- Update the default Helm configuration to use R and Python auto-detection.
- There is also an opportunity to simplify the Package Manager docker image, but that is out of the scope of this repo.
