### ISSUE TITLE
Provide docs and template to make it easy to use SCIM with Workbench

### ISSUE THREAD

**Issue by tnederlof** [rstudio/helm#497]
Starting in 2024.04.0 Workbench supports user provisioning via SCIM for certain IdPs. It would be really helpful to users of the helm chart to have a quick way to setup the proper token for this to work + documentation on the steps needed specific to K8s/Helm.

The steps from what I can tell are:

1. In `conf.server.rserver.conf` add: `user-provisioning-enabled: 1`
2. Create a `Secret` containing a token (should give guidance on how to create one)
3. Add the following to `values.yaml`
```
pod:
  env:
    - name: WORKBENCH_USER_SERVICE_AUTH_TOKEN_PATH
      value: "/etc/scim-token/scim_token"
  volumes:
    - name: secret-volume
      secret:
        secretName: scim-token
  volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/scim-token"
```
