### ISSUE TITLE
Slow deployment of Workbench when running in AWS EKS Fargate

### ISSUE THREAD

**Issue by Cecilsingh** [rstudio/helm#636]
Hi Team, we've had two clusters on EKS - the first one is using managed nodes which worked fine prior to its decommissioning. The second one is using EKS fargate. I've noticed that the Fargate nodes takes substantially longer to pull an image, both for deployment of the Workbench pod and session pods. Typically this takes approximately 10 minutes. Images are not cached either, so a new image pull is created on every session launch, resulting in each session taking ~10 minutes to start. See below:
![Image](https://github.com/user-attachments/assets/577ef9e4-de36-4ebb-bd89-379331998425)

 The values.yaml file is also very minimal:
```
userCreate: true
userName: "rstudio"
userPassword: "rstudio"
license:
  key: **Omitted**
homeStorage:
  create: false
  name: "efs-claim"
  path: "/home"
  mount: true
  storageClassName: "efs-sc"
  accessModes:
    - ReadWriteMany
  requests:
    storage: "2Gi"
```

Is this a known issue with EKS Fargate, or are there any additional components needed for Workbench to work with EKS fargate?
