### ISSUE TITLE
Order of resource profiles in configmap

### ISSUE THREAD

**Issue by michaelmayer2** [rstudio/helm#643]
When defining `launcher.kubernetes.resources.conf` in the helm chart like 

<p align="left">
    <img src="https://github.com/user-attachments/assets/b79fb0be-8e01-4ca8-ad88-25f527a29a5c" alt="x" width="200">
</p>

The resulting configmap seems to "sort" the resource profiles putting the "100 %" at the start:

<p align="left">
    <img src="https://github.com/user-attachments/assets/d910a307-653b-4940-8e14-c7ca48f49ab4" alt="x" width="300">
</p>

It would be nice to respect the order of which the resource profiles are put into values.yaml given the fact that it is the order of the profiles in `launcher.kubernetes.resources.conf` that determines the order the resource profiles are shown in the workbench UI.

**Comment by michaelmayer2** [comment]
@sebampuero

**Comment by michaelmayer2** [comment]
Same issue as in https://github.com/rstudio/helm/issues/346 but for resource profiles

**Comment by michaelmayer2** [comment]
After consulting with my favourite LLM it seems that we are using YAML maps for those configuration files in `values.yaml`. I am wondering if we simply need to change to a list with named properties ? 

“YAML maps (dictionaries) are inherently unordered. If you need to maintain order for key-value pairs, you should use a list of items with named properties”

**Comment by SamEdwardes** [comment]
I agree that it would be better if it wasn't sorted and the order you entered it in was preserved. In the meantime, however, if you need to preserve the order, you can do something like this. By prefixing with a number, the correct order is kept, and then by providing the name value, you can give a user-friendly name.

```yaml
# values.yaml
config:
  server:
    launcher.kubernetes.resources.conf:
      "01-small":
        name: Small
        cpus: 1
        mem-mb: 1024
      "02-large":
        name: Large
        cpus: 2
        mem-mb: 2048
```
