### ISSUE TITLE
RSW: OpenID Connect auth

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#74]
I am currently mounting the `openid-client-secret` via

```yml
config:
  server:
    openid-client-secret:
      client-id: rsw
      client-secret: $SECRET
```

Everything looks fine in the container, however I noticed that the permissions are too open:

```
ls -ld /mnt/configmap/rstudio/openid-client-secret
lrwxrwxrwx 1 root root 27 Nov  3 13:35 /mnt/configmap/rstudio/openid-client-secret -> ..data/openid-client-secret
```

When authenticating, I am getting an "unauthorized user" response from the IDP. Could the wrong permissions be the root cause for this?
Because the mount is read-only, I can't change them inside the container.
The logs on the IDP side look good, i.e. don't state that something was wrong.
I don't see anything helpful in the RSW logs yet.

I've mirrored the setup of an already working OIDC connection from a plain docker RSW instance, hence I am quite certain the settings are correct.

**Comment by colearendt** [comment]
Fantastic point! So you want to mount like this to get the permissions set properly on this file:
```
config:
  secret:
    openid-client-secret:
      client-id: rsw
      client-secret: $SECRET
```

The "Unauthorized user" message usually means that the shell account does not exist within the container. This is an unfortunate requirement that we are hoping to remove in the future, but at present, is currently required.

The "dev" version of the chart (`helm template --devel rstudio/rstudio-workbench`) has `sssd` running in the workbench container if you have a directory that you can use for provisioning users. Alternatively, you can write your own startup script / service that provisions users - articulated here: https://github.com/rstudio/helm/tree/main/charts/rstudio-workbench#user-provisioning.

I thought workbench enforced permissions on this file, but usually a permission enforcement on file permissions would issue a more dire message (or app failure).
