### ISSUE TITLE
RSW: default `sssd` template is not valid

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#79]
With the default `sssd` dummy template, `sssd` complains during startup

chart `v0.5-rc4`

```
(Fri Nov  5 07:58:44:879305 2021) [sssd] [sss_ini_get_config] (0x0020): Config merge error: File /etc/sssd/conf.d/..data did not match provided patterns. Skipping.
(Fri Nov  5 07:58:44:879322 2021) [sssd] [sss_ini_get_config] (0x0020): Config merge error: File /etc/sssd/conf.d/mysssd did not match provided patterns. Skipping.
(Fri Nov  5 07:58:44:879325 2021) [sssd] [sss_ini_get_config] (0x0020): Config merge error: File /etc/sssd/conf.d/..2021_11_05_07_56_24.441839353 did not match provided patterns. Skipping.
(Fri Nov  5 07:58:44:879329 2021) [sssd] [sss_ini_get_config] (0x0020): Config merge error: Errors detected while parsing: /etc/sssd/conf.d/mysssd.conf.
(Fri Nov  5 07:58:44:879332 2021) [sssd] [sss_ini_get_config] (0x0020): Config merge error: Error (8) on line 1: Failed to read line.
(Fri Nov  5 07:58:44:879335 2021) [sssd] [sss_ini_get_config] (0x0020): Config merge error: Due to errors file /etc/sssd/conf.d/mysssd.conf is not considered. Skipping.
```

I am not fully sure if this really causes a startup abort.

One should usually always set this anyhow for automatic user provisioning, but maybe the default template could at least make `sssd` happy on a basic level :)

**Comment by colearendt** [comment]
Weeeird! Is this with a values file present? Do you mind sharing your values file? Or at least the `config.userProvisioning` part?

**Comment by pat-s** [comment]
Sure.

I was using

```yml
  userProvisioning:
    mysssd.conf:
      sssd:
        config_file_version: 2
        services: nss, pam
        domains: rstudio.com
      domain/rstudio.com:
        id_provider: ldap
        auth_provider: ldap
```

which is the example shown in the README.
But this seems also auto-populated when not defining it.

I did not expect this to work for our setup but just wanted to see how it maps in the pod.
At first I thought this triggers a startup failure of the `rstudio` container but maybe not - my current startup issue might have its root somewhere else.
