### ISSUE TITLE
RSC: allow unsetting `RPackageRepository` defaults

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#93]
I have not found a way to unset the `RPackageRepository` default repos.

I'd like to make use of the `"repos"` defined within the respective R versions of the custom image I am using.

The following attempts were not valid

```yml
# errors during pod deployment
config:
  'RPackageRepository "CRAN"':
    URL: null
  'RPackageRepository "RSPM"':
    URL: null
```

```yml
# results in repos = NA
config:
  'RPackageRepository "CRAN"': null
  'RPackageRepository "RSPM"': null
```

AFAICS the `RPackageRepository` values should be optional (judging from the RSC admin guide) and if not set, the respective "repos" options of the R version are used.
I see the motivation for setting defaults for this in the helm chart.
It would be great if there was an option to unset these, however.
