### ISSUE TITLE
RSC: GitCredential values do not seem to get accepted

### ISSUE THREAD

**Issue by pat-s** [rstudio/helm#94]
We have a GitCredential set as follows

```yml
config:
  'GitCredential "GitHub"':
    Host: "github.com"
    Username: "pat-s"
    Protocol: "https"
    # encrypted
    Password: 427WcMVhuVDPKfcsiJwn2uUUqjydb3GTf3NxnlZE0Jsw387UPQ2WSzQE8/lBpjaMHip9U6Tzd62lxkw4U4D5fPvB7Cs88796al7EqgMzDys=
```

However, installations from private GH repos do not work for deployments requiring such.
The encrypted PAT works locally in a vanilla session when trying to install from a private repo.

I noticed the values are passed without quotes into `rstudio-connect.gcfg` within the pods - could this be a potential issue preventing RSC to read the configured values?
